apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasources
data:
{{ (.Files.Glob "files/grafana/provisioning/datasources/*").AsConfig | indent 2 }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-dashboards-provider
data:
{{ (.Files.Glob "files/grafana/provisioning/dashboards/*").AsConfig | indent 2 }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-dashboards
data:
{{ (.Files.Glob "files/grafana/dashboards/*").AsConfig | indent 2 }}
---
apiVersion: v1
kind: Service
metadata:
  name: grafana
  labels: { app: grafana }
spec:
  selector: { app: grafana }
  ports:
    - { name: http, port: 3000, targetPort: 3000 }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
spec:
  replicas: 1
  selector: { matchLabels: { app: grafana } }
  template:
    metadata:
      labels: { app: grafana }
    spec:
      containers:
        - name: grafana
          image: grafana/grafana:11.2.0
          env:
            - { name: GF_AUTH_ANONYMOUS_ENABLED, value: "true" }
            - { name: GF_AUTH_ANONYMOUS_ORG_ROLE, value: "Admin" }
            - { name: GF_AUTH_DISABLE_LOGIN_FORM, value: "true" }
            - { name: GF_INSTALL_PLUGINS, value: "grafana-clickhouse-datasource" }
          ports:
            - { containerPort: 3000, name: http }
          volumeMounts:
            - { name: datasources, mountPath: /etc/grafana/provisioning/datasources }
            - { name: dashprovider, mountPath: /etc/grafana/provisioning/dashboards }
            - { name: dashboards, mountPath: /var/lib/grafana/dashboards }
      volumes:
        - { name: datasources, configMap: { name: grafana-datasources } }
        - { name: dashprovider, configMap: { name: grafana-dashboards-provider } }
        - { name: dashboards, configMap: { name: grafana-dashboards } }
